web-assets-path = "web/dist"

authentication-key = ""
encryption-key = ""
csrf-authentication-key = ""

sock-name = "/tmp/stoptabnabbing.sock"
allowed-origins = ["http://localhost:8080", "https://stoptabnabbing.online"]
